spring:
  application:
    name: drdoc

server:
  port: 8080

ollama:
  base-url: http://localhost:11434
  chat-model: qwen2.5-coder:7b
  embedding-model: nomic-embed-text:v1.5

qdrant:
  host: localhost
  port: 6334
  collection-name: documents
